# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_graph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatpressure',
            name='created',
        ),
        migrations.RemoveField(
            model_name='seatpressure',
            name='pressure',
        ),
    ]
