# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('health_graph', '0002_auto_20160325_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatpressure',
            name='average',
            field=models.FloatField(default=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seatpressure',
            name='minutes',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 25, 11, 20, 15, 758291, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seatpressure',
            name='seat_count',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
